#!/bin/bash

if [ -z "$1" ]; then
    echo "Usage: $0 <source_file.c>"
    exit 1
fi

gcc -o "${1%.c}.out" "$1" -I/usr/include/postgresql -lpq -w
if [ $? -eq 0 ]; then
    ./"${1%.c}.out" "${@:2}"
    rm -f "${1%.c}.out"
else
    echo "Compilation failed."
fi